/*
 * generated by Xtext 2.10.0
 */
package org.ovirt.api.model


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class SpecStandaloneSetup extends SpecStandaloneSetupGenerated {

	def static void doSetup() {
		new SpecStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
